### ISSUE TITLE
nCoV-2019_64 and nCOV-2019_72 (V3) primers drop off 

### ISSUE THREAD

**Issue by EY639** [artic-network/primer-schemes#9] opened 2021-06-01 09:56 UTC
Hi team,

First, thank you for your great work.

The whole V3 primer set was working perfectly. But recently, we continuously see nCoV-2019_64 and nCOV-2019_72 primers dropped off. Recent samples are highly related to B.1.617 and they all share the primer dropped off issue. Not sure the problem relates to specific variants? 

Could you please provide any advice? 

Best,
Eva
![screenshot](https://user-images.githubusercontent.com/31894258/120304785-0058cf00-c2c8-11eb-8009-dd3701232261.jpg)

**Comment by szufan** [comment] 2021-06-30 00:13
Hi Eva. I'm not on the team, but we have observed A72 dropout in Deltas as well. There's a good preprint looking at similar issues: https://www.medrxiv.org/content/10.1101/2021.06.01.21258181v1.full-text 

In our case, though, the A72 dropout is likely being caused by a deletion in the region of primer 72_Right. Hopefully, these dropouts will be resolved with ARTIC V4.

**Comment by BioWilko** [comment] 2023-06-09 11:22
These problems were fortunately resolved in later scheme versions.

**Closed as completed by BioWilko** 2023-06-09 11:22 UTC
